#!/usr/bin/bash
# a bash script to display information about domains and subdomains

get_subDomainInfo () {
	# dig $2.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$2" '{ print "The subdomain " subdom " is a $4 record and points to $5"}'
	dig "$2"."$1" | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$2" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'

	return 0
}

get_allSubDomainsInfo () {

	subdomains=("www" "lb-01" "web-01" "web-02")
		
	for subdomain in "${subdomains[@]}"
	do
		# dig $subdomain.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " "$4" " record and points to " "$5"}'a
		dig "$subdomain"."$1" | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done

	return 0
}

# determine how many args passed
if [ $# -eq 2 ]; then
	get_subDomainInfo "$1" "$2"
else
	get_allSubDomainsInfo "$1"
fi
