#!/usr/bin/env bash
#  a Bash script that transfers a file from a client to a server

if [ $# -le 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	FILE=$1
	IP=$2
	USERNAME=$3
	SSH_KEY=$4
	scp -i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$FILE" "$USERNAME"@"$IP":~/ 

fi
