#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine and install nginx web server
PACKAGE="nginx"

sudo apt-get update -y
sudo apt-get install "$PACKAGE" -y
service nginx restart
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!">/var/www/html/index.html
