#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine and install nginx web server additionally
# configures redirection
PACKAGE="nginx"

if dpkg-query -l "$PACKAGE" > /dev/null 2>&1; then
        echo "$PACKAGE - has already been installed"

        if [[ -d "/var/www/html" ]]; then
                chown -R "$USER":"$USER" /var/www/html
                echo "Hello World!">/var/www/html/index.html
        fi
	NEW_RULE="\\\n\tlocation = /redirect_me/ {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
	sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup
	sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

	# adds a 404 error handler
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
	NOT_FOUND_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
	sudo sed -i "53i $NOT_FOUND_RULE" /etc/nginx/sites-available/default
else

	sudo apt update -y
        sudo apt install "$PACKAGE" -y
        if [[ -d "/var/www/html" ]]; then
                chown -R "$USER":"$USER" /var/www/html
                echo "Hello World!">/var/www/html/index.html
        fi
	NEW_RULE="\\\n\tlocation = /redirect_me/ {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
	sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup
	sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default
	# adds a 404 error handler
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
	NOT_FOUND_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
	sudo sed -i "53i $NOT_FOUND_RULE" /etc/nginx/sites-available/default
fi
sudo service nginx restart
