#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Check if password argument is provided
if [ -z "$1" ]; then
  echo "Error: Please provide the MySQL root password as an argument."
  exit 1
fi

# Define variables
MYSQL_USER="root"
MYSQL_PASSWORD="$1"
BACKUP_FILE="backup.sql"
TODAY=$(date +%d-%m-%Y)
ARCHIVE_FILE="$TODAY.tar.gz"

# Dump all databases
mysqldump -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --all-databases > $BACKUP_FILE
# Create compressed archive
tar -czvf "$ARCHIVE_FILE" $BACKUP_FILE
