#include <stdio.h>
char *_strncat(char *dest, char *src, int n);
int _strlen(char *str);
char *_strcat(char *dest, char *src);
int _putchar(char c);
char *cap_string(char *);
int _inarray(int *arr, int len, int n);
char *string_toupper(char *);
void reverse_array(int *a, int n);
int _strcmp(char *s1, char *s2);
char *_strncpy(char *dest, char *src, int n);
char *leet(char *);
int str_indexOf(char c, char *enc_lettr);
char *rot13(char *);
void aschii_tr_table(int *, int, int, int);
void print_number(int n);
void display_number(int rev_digit, int sign, int org_dig_len, int rev_dig_len);
int reverse_number(int digit, int length);
int get_digit_length(int digit);
int power(int base, int exp);
