#!/usr/bin/env bash
# a Bash script that configures an Ubuntu
# server with the below requirements. 
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
# echo "127.0.0.2	localhost" > ~/hosts.new
# echo "8.8.8.8	facebook.com" >> ~/hosts.new
sudo sed -i -E 's/(([0-9]+\.?){4}\slocalhost)/# \1/g' ~/hosts.new
sudo sed -i 's/(([0-9]+\.?){4}\sfacebook)/# \1/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
