#!/usr/bin/env bash
# a Bash script that displays all active
# IPv4 IPs on the machine it’s executed on.

#ifconfig -a | grep -E "\binet\b" | cut -d " " -f 10a
ifconfig | grep -Eo "inet ([0-9]+\.)+[0-9]+" | cut -d " " -f 2
